css
cells

^'
.float		{float:left;}

.event-blue { background-color: #E1E8F1;  border-top: 1px solid #53868B; border-left: 1px solid #53868B ; border-right: 1px solid #53868B ; border-bottom: 1px solid #53868B ; position:absolute;}
.event-pink { background-color: #F1E8E1; border-top: 1px solid #8B3E2F; border-left: 1px solid #8B3E2F ; border-right: 1px solid #8B3E2F ; border-bottom: 1px solid #8B3E2F ;position:absolute;}
.event-green { background-color: #E8F1E1; border-top: 1px solid #6E8B3D; border-left: 1px solid #6E8B3D ; border-right: 1px solid #6E8B3D ; border-bottom: 1px solid #6E8B3D ;position:absolute;}
.event-cyan { background-color: #E1F1E8; border-top: 1px solid #008B8B; border-left: 1px solid #008B8B ; border-right: 1px solid #008B8B ; border-bottom: 1px solid #008B8B ;position:absolute;}
.event-orange { background-color: #F1E1E8; border-top: 1px solid #CD6600; border-left: 1px solid #CD6600 ; border-right: 1px solid #CD6600 ; border-bottom: 1px solid #CD6600 ; position:absolute;}

.todo {  border-top: 1px solid #CDC8B1; border-left: 1px solid #CDC8B1 ; border-right: 1px solid #CDC8B1 ; border-bottom: 1px solid #CDC8B1 ;position:absolute; height:34px;}

.hour { width:90px;height:25px;background-color: #FFFFFF; border-bottom: 1px solid #CDC8B1;border-left: 1px solid #CDC8B1;border-right: 1px solid #CDC8B1;border-top: 1px solid #CDC8B1;position:absolute; }

.hour-today { width:90px;height:25px;background-color: #F0F0F0; border-bottom: 1px solid #CDC8B1;border-left: 1px solid #CDC8B1;border-right: 1px solid #CDC8B1;border-top: 1px solid #CDC8B1;position:absolute; }


.calendar-blue { width:90px;font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px;background-color: #E1E8F1;  border-top: 1px solid #53868B; border-left: 1px solid #53868B ; border-right: 1px solid #53868B ; border-bottom: 1px solid #53868B ; position:absolute;color:#53868B;}
.calendar-pink { width:90px;font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px;background-color: #F1E8E1; border-top: 1px solid #8B3E2F; border-left: 1px solid #8B3E2F ; border-right: 1px solid #8B3E2F ; border-bottom: 1px solid #8B3E2F ;position:absolute;color:#8B3E2F;}
.calendar-green {width:90px; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px;background-color: #E8F1E1; border-top: 1px solid #6E8B3D;border-bottom: 1px solid #6E8B3D ; border-left: 1px solid #6E8B3D ; border-right: 1px solid #6E8B3D ;position:absolute; color:#6E8B3D;}
.calendar-cyan { width:90px;font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px;background-color: #E1F1E8; border-top: 1px solid #008B8B; border-left: 1px solid #008B8B ; border-right: 1px solid #008B8B ; border-bottom: 1px solid #008B8B ;position:absolute;color:#008B8B;}
.calendar-orange { width:90px;font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px;background-color: #F1E1E8; border-top: 1px solid #CD6600; border-left: 1px solid #CD6600 ; border-right: 1px solid #CD6600 ; border-bottom: 1px solid #CD6600 ; position:absolute;color:#CD6600;}


'