css
fonts
	^ '			
.grey2 			{ font-family: Verdana, Geneva, Arial, Helvetica, sans-serif; font-size: 9px; color: #666666; }	
				
.weekNav {cursor: pointer;float:left; font-family: Verdana, Geneva, Arial, Helvetica, sans-serif; font-size: 9px; color: #6495ED; font-weight: 900;}
	
.weekNumber {float:left; font-family: Verdana, Geneva, Arial, Helvetica, sans-serif; font-size: 9px; color: #6495ED; font-weight: bold; width:500px; text-align: center;}	
				
.todo-cyan 			{ font-family: Verdana, Geneva, Arial, Helvetica, sans-serif; font-size: 9px; color: #006666; }	
.todo-green				{ font-family: Verdana, Geneva, Arial, Helvetica, sans-serif; font-size: 9px; color: #006600; }
.todo-pink 			{ font-family: Verdana, Geneva, Arial, Helvetica, sans-serif; font-size: 9px; color: #660303; }
.todo-blue 			{ font-family: Verdana, Geneva, Arial, Helvetica, sans-serif; font-size: 9px; color: #000066; }	
.todo-orange 			{ font-family: Verdana, Geneva, Arial, Helvetica, sans-serif; font-size: 9px; color: #663333; }	
	
	
			
.hours 			{width:30px;height:25px;background-color: #F2F2F2;font-family: Verdana, Geneva, Arial, Helvetica, sans-serif; font-size: 9px; color: #666666;}


			
.blue 			{ font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px; color: #0066FF; }
.cyan 			{ font-family: Verdana, Geneva, Arial, Helvetica, sans-serif; font-size: 9px; color: #006666; }	
.green				{ font-family: Verdana, Geneva, Arial, Helvetica, sans-serif; font-size: 9px; color: #006600; }
.pink 			{ font-family: Verdana, Geneva, Arial, Helvetica, sans-serif; font-size: 9px; color: #660303; }
		
.orange			{ font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px; color: #FF6600; }
			
.red 			{ font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px; color: #FF0000; }
			
.alarm 			{ font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px; color: #FF0000; font-weight: 900; }			
			
.date 			{ font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px; text-align:center; color: #0066FF;width:90px; }

.date-today			{ font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px; text-align:center; color: #0066FF;width:90px; font-weight: 900; }

.grey 			{ font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px; color: #A1A5A9; }

.eventfont 		{ font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px; color: #FFFFFF; }


'