css
miniCalendar

^'

.calendarPrevious{cursor: pointer; selectable: false; float:left; font-family: Verdana, Geneva, Arial, Helvetica, sans-serif; font-size: 9px; color: #6495ED; font-weight: 900;}

.calendar {font-family: Verdana, Geneva, Arial, Helvetica, sans-serif; font-size: 9px; color: #6495ED;}

.calendarMonth {float:left; font-family: Verdana, Geneva, Arial, Helvetica, sans-serif; font-size: 9px; color: #6495ED; width:160px; text-align:center; font-weight: 900;}

.calendarNext{cursor: pointer; float:left;  selectable: false; font-family: Verdana, Geneva, Arial, Helvetica, sans-serif; font-size: 9px; color: #6495ED; font-weight: 900;}

.calendarTitle {font-family: Verdana, Geneva, Arial, Helvetica, sans-serif; font-size: 10px; background-color: #6495ED; color: #FFFFFF; font-weight: 900;text-align:center; width:20px; }

.calendarDate {cursor: pointer;font-family: Verdana, Geneva, Arial, Helvetica, sans-serif; font-size: 10px; color: #6495ED; font-weight: 600; text-align:center;width:20px; }

.calendarArchiveDate {cursor: pointer;font-family: Verdana, Geneva, Arial, Helvetica, sans-serif; font-size: 10px; background-color: #6495ED; color: #FFFFFF; font-weight: 800; text-align:center;width:20px; }

.calendarNavigation { align:center;}

.calendarMouseOver {border-top: 1px solid #6495ED;  border-bottom: 1px solid #6495ED;  border-left: 1px solid #6495ED;  border-right: 1px solid #6495ED; }

.inplace { width:200px; z-index:5;}

.calendar-date {cursor: pointer; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 11px; color: #0066FF;}

'