accessing-exporting
goofyCardStringExport
^'BEGIN:VCARD' , String crlf ,
'VERSION:2.1' , String crlf ,
'N:Tschannen;Markus;;;'  , String crlf ,
'FN:Markus Tschannen' , String crlf ,
'BDAY:1980-10-30' , String crlf ,
'ADR;TYPE=home:;;Neufeldstrasse 11;Bern;;3012;Schweiz' , String crlf ,
'TEL;TYPE=home;TYPE=voice:+41 31 302 08 56' , String crlf ,
'TEL;TYPE=cell;TYPE=home:+41 78 845 24 12' , String crlf ,
'END:VCARD' , String crlf